on: push
name: macos
jobs:
  checks:
    name: run
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/private/var/tmp/_bazel_runner"
        key: bazel-${{ runner.os }}-${{ hashFiles('WORKSPACE', '.bazelrc', 'third_party/*', '**/BUILD') }}

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.18.0/bazelisk-darwin"
        mv bazelisk-darwin bazel
        chmod +x bazel

    - name: Build
      run: ./bazel build //:main
