on: push
name: windows
jobs:
  checks:
    name: run
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master

    - name: Add tar to path for cache
      run: echo "C:\msys64\usr\bin" >> $env:GITHUB_PATH

    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: C:\_bzl
        key: bazel-${{ runner.os }}-${{ hashFiles('WORKSPACE', '.bazelrc', 'third_party/*', '**/BUILD') }}

    - name: Install bazelisk
      run: |
        curl -LO https://github.com/bazelbuild/bazelisk/releases/download/v1.18.0/bazelisk-windows-amd64.exe

    - name: Build
      run: ./bazelisk-windows-amd64.exe --output_user_root=C:\_bzl build --cxxopt /std:c++20 //:main

    - name: Shutdown
      run: ./bazelisk-windows-amd64.exe --output_user_root=C:\_bzl shutdown

    - name: Remove symlinks from cache
      run: (Get-Item C:\_bzl\*\install).Delete()
